"""Protocol interfaces for service dependencies.

Services depend on these Protocols, not concrete adapter implementations.
This keeps the dependency direction clean: adapters implement Protocols,
services consume them.

The package is organised topically — consumers always deep-import via
``from services.protocols import X`` regardless of the host module:

- ``transport``: external system clients (RomM REST, SGDB REST, Steam IPC).
- ``determinism``: ``Clock`` / ``UuidGen`` / ``Sleeper`` test seams.
- ``persistence``: on-disk plugin settings and plugin metadata.
- ``paths``: RetroDECK path getters, system/core resolution, ES-DE
  read/write seams.
- ``infra``: cross-cutting callable seams (event emit, debug log,
  exists probe, cross-service callable bundles).
- ``files``: filesystem seams owning raw POSIX-style file I/O per
  service subtree.
- ``cross_service``: narrowly-typed multi-method seams one service
  exposes to another so services remain independent.
"""

from __future__ import annotations

from services.protocols.content_provider import CatalogueReader, CatalogueSourceStore, DownloadResolverReader
from services.protocols.cross_service import (
    AchievementsReader,
    ActiveCoreReader,
    ActiveDownloadRomIdsFn,
    AdoptionCandidateProbeFn,
    ArtworkManager,
    ArtworkRemover,
    BiosChecker,
    DeviceForgetFn,
    DeviceIdProvider,
    DiscResolver,
    DownloadTargetGateFn,
    InstalledRomFilesRemoverFn,
    InstalledRomRemoverFn,
    LaunchGateDriftReader,
    LaunchGateInstalledChecker,
    LaunchGateRomLookup,
    LaunchGateSaveStatusReader,
    MigrationPendingFn,
    PlaytimeScopeNoticeClearFn,
    PruneSaveCoordinator,
    ReachabilityProbeFn,
    RelaunchOptionsReader,
    RetryStrategy,
    RomInstallRecorder,
    RomLaunchPathReader,
    RomRelaunchItemReader,
    RomRemoverProvider,
    SaveDriftProbeFn,
    SaveInventoryBuilderFn,
    SaveQuarantineFn,
    SaveSortChangeFn,
    SaveSortingProvider,
    SessionAchievementSync,
    SessionMigrationReader,
    SessionPlaytimeRecorder,
    SessionPostExitSync,
    SiblingSupersedeFn,
    SiblingSupersedeProvider,
    VersionSwitcherFn,
)
from services.protocols.determinism import Clock, Sleeper, UuidGen
from services.protocols.files import (
    AdoptionMoveStore,
    CoverArtFileStore,
    DataLocationStore,
    DirectoryFileListerFn,
    DownloadFileStore,
    FirmwareFileStore,
    MigrationFileStore,
    PruneArtifactStore,
    RecoveryBundleStore,
    RomFileStore,
    SaveFileStore,
    SgdbArtworkCache,
    SteamRecoveryStore,
)
from services.protocols.infra import (
    ComputeSyncActionFn,
    DebugLogger,
    DownloadQueueCleanup,
    EventEmitter,
    GameProcessControl,
    HostnameReader,
    MachineIdReader,
    PathExistsReader,
    PendingSyncReader,
    RendererGcFn,
    RendererRssFn,
    ResolvedPathFn,
    ResolveUploadConflictFn,
)
from services.protocols.paths import (
    CoreInfoProvider,
    CoreNameProviderFn,
    CoreResolverFn,
    FirmwareFolderVerdictFn,
    FirmwareResolver,
    InstallationChangeFn,
    PlatformCoreReader,
    RetroArchConfigReader,
    RetroArchCoreInfoReader,
    RetroArchSaveLayoutProvider,
    RetroArchSavestateLayoutProvider,
    RetroDeckPaths,
    SandboxLauncherFn,
    SystemKnownFn,
    SystemM3uSupportFn,
    SystemResolver,
    SystemSupportedExtensionsFn,
)
from services.protocols.persistence import (
    PluginMetadataReader,
    SettingsPersister,
)
from services.protocols.repositories import (
    BiosFileRepository,
    FirmwareCacheRepository,
    KvConfigRepository,
    PlatformSyncStateRepository,
    PlaytimeRepository,
    RomInstallRepository,
    RomMetadataRepository,
    RomRepository,
    RomSaveSyncStateRepository,
    SyncRunRepository,
)
from services.protocols.transport import (
    RomDetailReader,
    RomDownloadReader,
    RommAchievementsApi,
    RommApi,
    RommConnectionApi,
    RommDeviceApi,
    RommFirmwareApi,
    RommLibraryApi,
    RommLivenessApi,
    RommPlatformReader,
    RommPlaytimeApi,
    RommRomReader,
    RommSaveApi,
    RommSyncApi,
    RommTokenApi,
    RommVersion,
    SteamConfigStore,
    SteamGridDbApi,
)
from services.protocols.uow import UnitOfWork, UnitOfWorkFactory

__all__ = [
    "AchievementsReader",
    "ActiveCoreReader",
    "ActiveDownloadRomIdsFn",
    "AdoptionCandidateProbeFn",
    "AdoptionMoveStore",
    "ArtworkManager",
    "ArtworkRemover",
    "BiosChecker",
    "BiosFileRepository",
    "CatalogueReader",
    "CatalogueSourceStore",
    "Clock",
    "ComputeSyncActionFn",
    "CoreInfoProvider",
    "CoreNameProviderFn",
    "CoreResolverFn",
    "CoverArtFileStore",
    "DataLocationStore",
    "DebugLogger",
    "DeviceForgetFn",
    "DeviceIdProvider",
    "DirectoryFileListerFn",
    "DiscResolver",
    "DownloadFileStore",
    "DownloadQueueCleanup",
    "DownloadResolverReader",
    "DownloadTargetGateFn",
    "EventEmitter",
    "FirmwareCacheRepository",
    "FirmwareFileStore",
    "FirmwareFolderVerdictFn",
    "FirmwareResolver",
    "GameProcessControl",
    "HostnameReader",
    "InstallationChangeFn",
    "InstalledRomFilesRemoverFn",
    "InstalledRomRemoverFn",
    "KvConfigRepository",
    "LaunchGateDriftReader",
    "LaunchGateInstalledChecker",
    "LaunchGateRomLookup",
    "LaunchGateSaveStatusReader",
    "MachineIdReader",
    "MigrationFileStore",
    "MigrationPendingFn",
    "PathExistsReader",
    "PendingSyncReader",
    "PlatformCoreReader",
    "PlatformSyncStateRepository",
    "PlaytimeRepository",
    "PlaytimeScopeNoticeClearFn",
    "PluginMetadataReader",
    "PruneArtifactStore",
    "PruneSaveCoordinator",
    "ReachabilityProbeFn",
    "RecoveryBundleStore",
    "RelaunchOptionsReader",
    "RendererGcFn",
    "RendererRssFn",
    "ResolveUploadConflictFn",
    "ResolvedPathFn",
    "RetroArchConfigReader",
    "RetroArchCoreInfoReader",
    "RetroArchSaveLayoutProvider",
    "RetroArchSavestateLayoutProvider",
    "RetroDeckPaths",
    "RetryStrategy",
    "RomDetailReader",
    "RomDownloadReader",
    "RomFileStore",
    "RomInstallRecorder",
    "RomInstallRepository",
    "RomLaunchPathReader",
    "RomMetadataRepository",
    "RomRelaunchItemReader",
    "RomRemoverProvider",
    "RomRepository",
    "RomSaveSyncStateRepository",
    "RommAchievementsApi",
    "RommApi",
    "RommConnectionApi",
    "RommDeviceApi",
    "RommFirmwareApi",
    "RommLibraryApi",
    "RommLivenessApi",
    "RommPlatformReader",
    "RommPlaytimeApi",
    "RommRomReader",
    "RommSaveApi",
    "RommSyncApi",
    "RommTokenApi",
    "RommVersion",
    "SandboxLauncherFn",
    "SaveDriftProbeFn",
    "SaveFileStore",
    "SaveInventoryBuilderFn",
    "SaveQuarantineFn",
    "SaveSortChangeFn",
    "SaveSortingProvider",
    "SessionAchievementSync",
    "SessionMigrationReader",
    "SessionPlaytimeRecorder",
    "SessionPostExitSync",
    "SettingsPersister",
    "SgdbArtworkCache",
    "SiblingSupersedeFn",
    "SiblingSupersedeProvider",
    "Sleeper",
    "SteamConfigStore",
    "SteamGridDbApi",
    "SteamRecoveryStore",
    "SyncRunRepository",
    "SystemKnownFn",
    "SystemM3uSupportFn",
    "SystemResolver",
    "SystemSupportedExtensionsFn",
    "UnitOfWork",
    "UnitOfWorkFactory",
    "UuidGen",
    "VersionSwitcherFn",
]
